import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const translations = {
  es: {
    hello: 'Hola',
    publishGig: 'Publicar Gig',
    beSeller: 'Ser Vendedor',
    logout: 'Salir',
    wishlist: 'Mi Wishlist',
    darkMode: 'Modo oscuro',
    lightMode: 'Modo claro',
    heroTitle: 'Encuentra el servicio',
    heroTitleItalic: 'freelance',
    heroSubtitle: 'adecuado de inmediato',
    support24: 'Soporte 24 horas',
    securePay: 'Pago seguro',
    popularServices: 'Servicios populares',
    ctaTitle: '¿Listo para comenzar?',
    ctaSubtitle: 'Únete a miles de freelancers y clientes',
    ctaButton: 'Comenzar Ahora',
    access: 'Acceder',
    seller: 'Vendedor',
    from: 'Desde',
    noServices: 'No hay servicios disponibles en este momento',
    welcome: 'Bienvenido de nuevo',
    userOrEmail: 'Usuario o Correo',
    password: 'Contraseña',
    login: 'Iniciar Sesión',
    loggingIn: 'Entrando...',
    newHere: '¿Nuevo aquí?',
    createAccount: 'Crea una cuenta',
    createAccountTitle: 'Crear Cuenta',
    joinCommunity: 'Únete a la comunidad de creativos',
    fullName: 'Nombre Completo',
    username: 'Usuario (Nickname)',
    email: 'Correo Electrónico',
    register: 'Registrarse',
    registering: 'Registrando...',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    signIn: 'Inicia sesión',
    exploreServices: 'Explora Servicios Digitales',
    searchPlaceholder: 'Buscar servicios, cursos, recursos...',
    buyAndView: 'Ver y Comprar',
    noResults: 'Sin resultados',
    noResultsHint: 'Prueba con otras palabras o categoría',
    myPurchases: 'Mis Compras',
    myPublications: 'Mis Publicaciones',
    requestSeller: 'Solicitar ser Vendedor',
    pendingRequest: 'Tu solicitud está pendiente de aprobación.',
    editProfile: 'Editar',
    addDescription: 'Agrega una descripción editando tu perfil.',
    earningsPanel: 'Panel de Ganancias',
    availableBalance: 'Saldo disponible',
    totalEarned: 'Total ganado',
    completedSales: 'Ventas completadas',
    pending: 'Pendientes',
    avgPerSale: 'Promedio por venta',
    latestSales: 'Últimas ventas',
    noSalesYet: 'Aún no tienes ventas',
    noPurchasesYet: 'Aún no has realizado ninguna compra',
    close: 'Cerrar',
    categories: {
      all: 'Todos',
      gig: 'Servicio / Gig',
      course: 'Curso Digital',
      download: 'Descargable',
      subscription: 'Suscripción',
      product: 'Producto',
      consulting: 'Consultoría',
      design: 'Diseño Gráfico',
      webDev: 'Dev Web',
      marketing: 'Marketing',
      music: 'Música / Audio',
    },
  },

  en: {
    hello: 'Hello',
    publishGig: 'Post a Gig',
    beSeller: 'Become a Seller',
    logout: 'Sign Out',
    wishlist: 'My Wishlist',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    heroTitle: 'Find the right',
    heroTitleItalic: 'freelance',
    heroSubtitle: 'service immediately',
    support24: '24-hour support',
    securePay: 'Secure payment',
    popularServices: 'Popular services',
    ctaTitle: 'Ready to get started?',
    ctaSubtitle: 'Join thousands of freelancers and clients',
    ctaButton: 'Start Now',
    access: 'Sign In',
    seller: 'Seller',
    from: 'From',
    noServices: 'No services available at this time',
    welcome: 'Welcome back',
    userOrEmail: 'Username or Email',
    password: 'Password',
    login: 'Sign In',
    loggingIn: 'Signing in...',
    newHere: 'New here?',
    createAccount: 'Create an account',
    createAccountTitle: 'Create Account',
    joinCommunity: 'Join the creative community',
    fullName: 'Full Name',
    username: 'Username (Nickname)',
    email: 'Email Address',
    register: 'Register',
    registering: 'Registering...',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign in',
    exploreServices: 'Explore Digital Services',
    searchPlaceholder: 'Search services, courses, resources...',
    buyAndView: 'View & Buy',
    noResults: 'No results',
    noResultsHint: 'Try different words or category',
    myPurchases: 'My Purchases',
    myPublications: 'My Listings',
    requestSeller: 'Become a Seller',
    pendingRequest: 'Your request is pending approval.',
    editProfile: 'Edit',
    addDescription: 'Add a description by editing your profile.',
    earningsPanel: 'Earnings Dashboard',
    availableBalance: 'Available balance',
    totalEarned: 'Total earned',
    completedSales: 'Completed sales',
    pending: 'Pending',
    avgPerSale: 'Avg per sale',
    latestSales: 'Latest sales',
    noSalesYet: "You don't have any sales yet",
    noPurchasesYet: "You haven't made any purchases yet",
    close: 'Close',
    categories: {
      all: 'All',
      gig: 'Service / Gig',
      course: 'Digital Course',
      download: 'Downloadable',
      subscription: 'Subscription',
      product: 'Product',
      consulting: 'Consulting',
      design: 'Graphic Design',
      webDev: 'Web Dev',
      marketing: 'Marketing',
      music: 'Music / Audio',
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(
    () => localStorage.getItem('language') || 'es'
  );

  const switchLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('language', newLang);
  };

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};